### ISSUE TITLE
The paper claims that it can be used in TTS, but is lack of TTS experiments.

### ISSUE THREAD

**Issue by splinter21** [hcy71o/AutoVocoder#1]
Acoustic model is hard to reconstruct the phase information, but autovocoder contains phase information in the 256 representation, so that the 256 version outperforms hifiganv1.
If it is used in TTS pipeline, that means the acoustic model has to learn reconstructing the phase information.
I don't think the TTS pipeline using autovocoder will outperform that using vocoder (e.g. hifiganv1), unless the author provides the  TTS experimental data.

**Comment by hcy71o** [comment]
> Acoustic model is hard to reconstruct the phase information, but autovocoder contains phase information in the 256 representation, so that the 256 version outperforms hifiganv1. If it is used in TTS pipeline, that means the acoustic model has to learn reconstructing the phase information. I don't think the TTS pipeline using autovocoder will outperform that using vocoder (e.g. hifiganv1), unless the author provides the TTS experimental data.

I think such a problem could arise in application of two-stage pipelines (e.g. FastSpeech2 + HiFi-V1).. where two modules are developed separately. Wouldn't the phase modeling problem be alleviated by predicting latent representation with implicit phase information?
I'll try to incorporate AutoVocoder to VITS in the same context, to experiment whether its prior (AM) can reliably reconstruct the latent representation including phase information.

**Comment by jacobjwebber** [comment]
Hi! I am the author of the AutoVocoder paper. 

This is a good point @splinter21 -- phase reconstruction does make generating the learned representations harder for the AM, as these representations contain phase information. Deciding where to reconstruct phase, by using end-to-end systems (like using AutoVocoder decoder with VITS), or by generating with an AM (as in AutoVocoder as a vocoder) is an interesting open problem!

I'm hoping to write more on this soon and publish more experiments. Thank you both for your interest in this paper! Feel free to get in touch with me if you want to discuss anything

Jacob

**Comment by wizardk** [comment]
> 



> Hi! I am the author of the AutoVocoder paper.
> 
> This is a good point @splinter21 -- phase reconstruction does make generating the learned representations harder for the AM, as these representations contain phase information. Deciding where to reconstruct phase, by using end-to-end systems (like using AutoVocoder decoder with VITS), or by generating with an AM (as in AutoVocoder as a vocoder) is an interesting open problem!
> 
> I'm hoping to write more on this soon and publish more experiments. Thank you both for your interest in this paper! Feel free to get in touch with me if you want to discuss anything
> 
> Jacob

Hi @jacobjwebber , did you do any experiment to compare with iSTFTNet? I'm curious about the comparison between AutoVocoder and iSTFTNet.
